annotations:
  max_scale_version: 29.10.2
  min_scale_version: 23.10.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: Home
  truecharts.org/max_helm_version: "3.14"
  truecharts.org/min_helm_version: "3.12"
  truecharts.org/train: stable
apiVersion: v2
appVersion: 1.0.0
dependencies:
  - name: common
    version: 17.4.2
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: CellGate Remote
home: https://github.com/vincent99/cellgate
kubeVersion: ">=1.24.0-0"
name: cellgate
sources:
  - https://github.com/vincent99/cellgate/tree/gh-pages/charts/stable/cellgate
  - https://hub.docker.com/r/vincent99/cellgate
type: application
version: 1.0.0
